const UP_ACTION = "UP_ACTION";
const DOWN_ACTION = "DOWN_ACTION";
const RESET_ACTION = "RESET_ACTION";
const UPDATE_COUNTER = "UPDATE_COUNTER";

export { UP_ACTION, DOWN_ACTION, RESET_ACTION, UPDATE_COUNTER };
